// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4owqdlXyrxnn_gyH9BBlLmL3Vjl2OkgY',
    appId: '1:966269973701:android:f68f1e99120d2cec2decac',
    messagingSenderId: '966269973701',
    projectId: 'test-frontend-5dbe7',
    storageBucket: 'test-frontend-5dbe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEX_BssLJ3V50kJeOj7uHX1Q4-75FxFfY',
    appId: '1:966269973701:ios:aed4866e8ef8ba702decac',
    messagingSenderId: '966269973701',
    projectId: 'test-frontend-5dbe7',
    storageBucket: 'test-frontend-5dbe7.appspot.com',
    iosClientId: '966269973701-79o8bfsam6f00fgfij6rrq9pva0lel5d.apps.googleusercontent.com',
    iosBundleId: 'com.dasafodev.test',
  );
}
